# -*- coding: utf-8 -*-
"""STRESS DETECTION FROM SPEECH USING TRANSFORMER-BASED DEEP LEARNING .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jg2rPVcarfXK0XvtN8iqQmxkr6HTMR58
"""

!pip install -q transformers==4.52.4
!pip install -q accelerate==1.7.0
!pip install -q datasets librosa evaluate seaborn

import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

from google.colab import drive
drive.mount('/content/drive')

import os

print(os.listdir('/content/drive/MyDrive'))

audio_folder = "/content/drive/MyDrive/audio_files/audio_files"

import os

audio_folder = "/content/drive/MyDrive/audio_files/audio_files"

print("Folder exists:", os.path.exists(audio_folder))

if os.path.exists(audio_folder):
    print("Total files:", len(os.listdir(audio_folder)))
    print("First 10 files:", os.listdir(audio_folder)[:10])

print(os.listdir('/content/drive/MyDrive'))

import os

print(os.listdir('/content/drive/MyDrive/audio_files'))

import pandas as pd

df = pd.read_csv('/content/Book 2(Sheet1).csv')

print(df.shape)
df.head()

print(df["STRESS_LEVEL"].unique())

df["label"] = df["STRESS_LEVEL"].map({
    "STRESSED": 1,
    "UNSTRESSED": 0
})

df["FILE_NAME"] = df["FILE_NAME"].str.lower()

import os

audio_folder = "/content/drive/MyDrive/audio_files/audio_files"

df["audio_path"] = df["FILE_NAME"].apply(
    lambda x: os.path.join(audio_folder, x)
)

import librosa

audio_list = []
label_list = []

for _, row in df.iterrows():

    try:

        speech, sr = librosa.load(
            row["audio_path"],
            sr=16000
        )

        audio_list.append(speech)
        label_list.append(int(row["label"]))

    except:
        pass

print("Audio:", len(audio_list))
print("Labels:", len(label_list))

audio_list = []
label_list = []

for _, row in df.iterrows():

    try:

        speech, sr = librosa.load(
            row["audio_path"],
            sr=16000
        )

        audio_list.append(speech)
        label_list.append(int(row["label"]))

    except Exception as e:
        print("Error loading:", row["audio_path"])
        print(e)

print("Audio:", len(audio_list))
print("Labels:", len(label_list))

print(df["FILE_NAME"].head())
print(df["audio_path"].head())

audio_folder = "/content/drive/MyDrive/audio_files"

import os

audio_folder = "/content/drive/MyDrive/audio_files"

df["audio_path"] = df["FILE_NAME"].apply(
    lambda x: os.path.join(audio_folder, x)
)

print(df["audio_path"].head())

audio_list = []
label_list = []

for _, row in df.iterrows():

    try:

        speech, sr = librosa.load(
            row["audio_path"],
            sr=16000
        )

        audio_list.append(speech)
        label_list.append(int(row["label"]))

    except Exception as e:
        print("Error:", row["audio_path"])
        print(e)

print("Audio:", len(audio_list))
print("Labels:", len(label_list))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    audio_list,
    label_list,
    test_size=0.2,
    random_state=42,
    stratify=label_list
)

print("Train:", len(X_train))
print("Test:", len(X_test))

import numpy as np
import librosa

aug_X_train = []
aug_y_train = []

for audio, label in zip(X_train, y_train):

    audio = np.array(audio, dtype=np.float32)

    # Original
    aug_X_train.append(audio)
    aug_y_train.append(label)

    # Noise
    noise = np.random.normal(0, 0.003, len(audio))
    aug_X_train.append(audio + noise)
    aug_y_train.append(label)

    # Time Shift
    shift = int(0.1 * len(audio))
    shifted = np.roll(audio, shift)
    aug_X_train.append(shifted)
    aug_y_train.append(label)

    # Pitch Shift
    pitched = librosa.effects.pitch_shift(
        y=audio,
        sr=16000,
        n_steps=2
    )
    aug_X_train.append(pitched)
    aug_y_train.append(label)

X_train = aug_X_train
y_train = aug_y_train

print("Training samples after augmentation:", len(X_train))
print("Testing samples:", len(X_test))

import numpy as np

X_train = [np.asarray(x, dtype=np.float32) for x in X_train]
X_test = [np.asarray(x, dtype=np.float32) for x in X_test]

from transformers import Wav2Vec2Processor

processor = Wav2Vec2Processor.from_pretrained(
    "facebook/wav2vec2-base"
)

from datasets import Dataset

train_dataset = Dataset.from_dict({
    "audio": X_train,
    "label": y_train
})

test_dataset = Dataset.from_dict({
    "audio": X_test,
    "label": y_test
})

def preprocess(batch):

    inputs = processor(
        batch["audio"],
        sampling_rate=16000
    )

    batch["input_values"] = inputs.input_values[0]

    return batch

train_dataset = train_dataset.map(preprocess)
test_dataset = test_dataset.map(preprocess)

train_dataset = train_dataset.remove_columns(["audio"])
test_dataset = test_dataset.remove_columns(["audio"])

print(train_dataset[0])

from transformers import Wav2Vec2ForSequenceClassification

model = Wav2Vec2ForSequenceClassification.from_pretrained(
    "facebook/wav2vec2-base",
    num_labels=2
)

model.freeze_feature_encoder()

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

def compute_metrics(pred):

    preds = np.argmax(
        pred.predictions,
        axis=1
    )

    precision, recall, f1, _ = precision_recall_fscore_support(
        pred.label_ids,
        preds,
        average="binary"
    )

    acc = accuracy_score(
        pred.label_ids,
        preds
    )

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

import torch

def data_collator(features):

    input_values = [f["input_values"] for f in features]

    batch = processor.pad(
        {"input_values": input_values},
        padding=True,
        return_tensors="pt"
    )

    batch["labels"] = torch.tensor(
        [f["label"] for f in features]
    )

    return batch

from transformers import TrainingArguments

training_args = TrainingArguments(

    output_dir="./stress_model",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=1e-6,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=15,

    weight_decay=0.01,

    logging_steps=10,

    report_to="none",

    load_best_model_at_end=True
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

import transformers
import accelerate

print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)

import torch
torch.cuda.empty_cache()

print(torch.cuda.get_device_name(0))

trainer.train()

import numpy as np

predictions = trainer.predict(test_dataset)

preds = np.argmax(
    predictions.predictions,
    axis=1
)

labels = predictions.label_ids

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(labels, preds)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

logs = trainer.state.log_history

losses = []

for log in logs:
    if "loss" in log:
        losses.append(log["loss"])

smooth_loss = pd.Series(losses).ewm(
    span=15
).mean()

plt.figure(figsize=(8,5))

plt.plot(
    smooth_loss,
    linewidth=3
)

plt.title("Training Loss Curve")
plt.xlabel("Training Steps")
plt.ylabel("Loss")

plt.grid(True)

plt.show()

results = trainer.evaluate()
print(results)

metrics = {
    'Accuracy': results['eval_accuracy'],
    'Precision': results['eval_precision'],
    'Recall': results['eval_recall'],
    'F1 Score': results['eval_f1']
}

plt.figure(figsize=(7,5))

plt.bar(
    metrics.keys(),
    metrics.values()
)

plt.ylim(0,1)

plt.title("Model Performance")
plt.ylabel("Score")

plt.show()

model.save_pretrained("final_model")
processor.save_pretrained("final_model")

!zip -r final_model.zip final_model

from google.colab import files

files.download("final_model.zip")

