# -*- coding: utf-8 -*-
"""Stress Detection from Speech Using Transformer-Based Deep Learning .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMD-bJjLUMZXri3Iug_pgBbuHv0tevxF
"""

import torch

print("GPU Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

from google.colab import drive
drive.mount('/content/drive')

!pip install -q transformers datasets accelerate evaluate librosa soundfile

import os
import librosa
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import seaborn as sns

from datasets import Dataset

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from transformers import (
    Wav2Vec2Processor,
    Wav2Vec2ForSequenceClassification,
    Trainer,
    TrainingArguments
)

df = pd.read_csv('/content/Book 2(Sheet1).csv')

print(df.head())
print(df.shape)
print(df.columns)

print(df.columns)

audio_folder = "/content/drive/MyDrive/audio_files/audio_files"

import os

audio_folder = "/content/drive/MyDrive/audio_files/audio_files"

print("Total Audio Files:", len(os.listdir(audio_folder)))
print(os.listdir(audio_folder)[:10])

!apt-get install ffmpeg -y

import os

input_folder = "/content/drive/MyDrive/audio_files/audio_files"
output_folder = "/content/wav_files"

os.makedirs(output_folder, exist_ok=True)

for file in os.listdir(input_folder):

    if file.endswith(".mp4"):

        input_path = os.path.join(input_folder, file)

        output_path = os.path.join(
            output_folder,
            file.replace(".mp4", ".wav")
        )

        os.system(
            f'ffmpeg -i "{input_path}" -ar 16000 -ac 1 "{output_path}" -loglevel quiet'
        )

print("Conversion Completed")

import os

print(
    "Total WAV Files:",
    len(os.listdir("/content/wav_files"))
)

df['FILE_NAME'] = df['FILE_NAME'].str.lower()

df['FILE_NAME'] = df['FILE_NAME'].str.replace(
    ".mp4",
    ".wav",
    regex=False
)

df['audio_path'] = df['FILE_NAME'].apply(
    lambda x: f"/content/wav_files/{x}"
)

print(
    df[['FILE_NAME','audio_path']].head()
)

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['STRESS_LEVEL'] = df['STRESS_LEVEL'].str.upper()

df['label'] = encoder.fit_transform(
    df['STRESS_LEVEL']
)

print("Classes:")
print(encoder.classes_)

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df['label']
)

print("Train:", len(train_df))
print("Test:", len(test_df))

from transformers import Wav2Vec2Processor

processor = Wav2Vec2Processor.from_pretrained(
    "facebook/wav2vec2-base"
)

import librosa

def load_audio(path):

    speech, sr = librosa.load(
        path,
        sr=16000
    )

    return speech

import librosa

def load_audio(path):

    speech, sr = librosa.load(
        path,
        sr=16000
    )

    return speech

from datasets import Dataset

def prepare_dataset(dataframe):

    audio_list = []
    label_list = []

    for _, row in dataframe.iterrows():

        speech = load_audio(
            row['audio_path']
        )

        audio_list.append(speech)

        label_list.append(
            int(row['label'])
        )

    return Dataset.from_dict(
        {
            "audio": audio_list,
            "label": label_list
        }
    )

train_dataset = prepare_dataset(train_df)

test_dataset = prepare_dataset(test_df)

print(train_dataset)
print(test_dataset)

def preprocess(batch):

    inputs = processor(
        batch["audio"],
        sampling_rate=16000
    )

    batch["input_values"] = inputs.input_values[0]

    return batch

train_dataset = train_dataset.map(
    preprocess
)

test_dataset = test_dataset.map(
    preprocess
)

train_dataset = train_dataset.remove_columns(
    ["audio"]
)

test_dataset = test_dataset.remove_columns(
    ["audio"]
)

print(train_dataset[0])

from transformers import Wav2Vec2ForSequenceClassification

model = Wav2Vec2ForSequenceClassification.from_pretrained(
    "facebook/wav2vec2-base",
    num_labels=2
)

from dataclasses import dataclass
import torch

@dataclass
class DataCollatorCTCWithPadding:

    processor: Wav2Vec2Processor

    def __call__(self, features):

        input_features = [
            {
                "input_values":
                feature["input_values"]
            }
            for feature in features
        ]

        labels = [
            feature["label"]
            for feature in features
        ]

        batch = self.processor.pad(
            input_features,
            padding=True,
            return_tensors="pt"
        )

        batch["labels"] = torch.tensor(labels)

        return batch

data_collator = DataCollatorCTCWithPadding(
    processor=processor
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

import numpy as np

def compute_metrics(pred):

    labels = pred.label_ids

    preds = np.argmax(
        pred.predictions,
        axis=1
    )

    return {

        "accuracy":
        accuracy_score(labels,preds),

        "precision":
        precision_score(labels,preds),

        "recall":
        recall_score(labels,preds),

        "f1":
        f1_score(labels,preds)
    }

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./stress_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=10,
    report_to="none"
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

results = trainer.evaluate()

print(results)

predictions = trainer.predict(
    test_dataset
)

preds = np.argmax(
    predictions.predictions,
    axis=1
)

labels = predictions.label_ids

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    labels,
    preds
)

print("Accuracy:", accuracy)

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score
)

print(
    "Precision:",
    precision_score(labels,preds)
)

print(
    "Recall:",
    recall_score(labels,preds)
)

print(
    "F1 Score:",
    f1_score(labels,preds)
)

from sklearn.metrics import classification_report

print(
    classification_report(
        labels,
        preds
    )
)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(
    labels,
    preds
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "Stress Detection Confusion Matrix"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

logs = trainer.state.log_history

losses = []

for log in logs:

    if "loss" in log:

        losses.append(
            log["loss"]
        )

plt.figure(figsize=(8,5))

plt.plot(losses)

plt.title(
    "Training Loss Curve"
)

plt.xlabel("Steps")
plt.ylabel("Loss")

plt.show()

model.save_pretrained(
    "stress_model"
)

processor.save_pretrained(
    "stress_model"
)

!zip -r stress_model.zip stress_model

import torch
import librosa

def predict_audio(path):

    audio, sr = librosa.load(
        path,
        sr=16000
    )

    inputs = processor(
        audio,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True
    )

    with torch.no_grad():

        logits = model(
            inputs.input_values
        ).logits

    pred = torch.argmax(
        logits,
        dim=1
    ).item()

    return encoder.inverse_transform(
        [pred]
    )[0]

import torch
import librosa

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model.to(device)

def predict_audio(path):

    audio, sr = librosa.load(
        path,
        sr=16000
    )

    inputs = processor(
        audio,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True
    )

    input_values = inputs.input_values.to(device)

    with torch.no_grad():

        logits = model(
            input_values
        ).logits

    pred = torch.argmax(
        logits,
        dim=1
    ).item()

    return encoder.inverse_transform(
        [pred]
    )[0]

predict_audio(
    "/content/wav_files/audio1.wav"
)

results = trainer.evaluate()

print(results)

predictions = trainer.predict(test_dataset)

preds = np.argmax(
    predictions.predictions,
    axis=1
)

labels = predictions.label_ids

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    labels,
    preds
)

print("Accuracy:", accuracy)

# Class distribution graph
df['STRESS_LEVEL'].value_counts().plot(kind='bar')
plt.title("Stress Level Distribution")
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

predictions = trainer.predict(test_dataset)

preds = np.argmax(
    predictions.predictions,
    axis=1
)

labels = predictions.label_ids

cm = confusion_matrix(labels, preds)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.show()

import matplotlib.pyplot as plt

logs = trainer.state.log_history

losses = []

for log in logs:
    if "loss" in log:
        losses.append(log["loss"])

plt.figure(figsize=(8,5))

plt.plot(losses, marker='o')

plt.title("Training Loss Curve")
plt.xlabel("Training Steps")
plt.ylabel("Loss")

plt.grid(True)

plt.show()

metrics = {
    'Accuracy': 0.75,
    'Precision': 0.7333,
    'Recall': 0.7857,
    'F1 Score': 0.7586
}

plt.figure(figsize=(7,5))

plt.bar(
    metrics.keys(),
    metrics.values()
)

plt.ylim(0,1)

plt.title("Model Performance Metrics")

plt.ylabel("Score")

plt.show()

!ls -lh /content/stress_model.zip

import os
os.makedirs("final_model", exist_ok=True)

model.save_pretrained("final_model")
processor.save_pretrained("final_model")

!zip -r final_model.zip final_model

!ls -lh final_model.zip

from google.colab import files
files.download("final_model.zip")

